direction: down

Start -> A

A: "Pick new target sentence(s) so that we have two"
B: "Present previously unseen vocabulary"
C: "Practice vocabulary with Spaced Repetition"
D: "Once all parts of a sentence are practiced, challenge the user to translate"

A <-> B
B <-> C
A <-> C

D -> A
B -> D
C -> D
