flowchart TD
    Start --> A["Pick new target sentence(s) so that we have two"] 
    B["Present previously unseen, needed vocabulary"] 
    C["Practice seen vocabulary, needed vocabulary with Spaced Repetition"]
    A<-->B
    B<-->C
    A<-->C
    D["Once all parts of a sentence are practiced, challenge the user to translate the given target sentence"]-->A
    B-->D
    C-->D